# Generated by Django 3.1.1 on 2020-09-09 02:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_home', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batting_pos', models.SmallIntegerField(default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.team')),
            ],
            options={
                'unique_together': {('player', 'team')},
                'order_with_respect_to': 'player',
            },
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', through='api.TeamMembership', to='api.Player'),
        ),
        migrations.CreateModel(
            name='RunningPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlateAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.SmallIntegerField(default=1)),
                ('outcome', models.CharField(choices=[('NOPA', 'No Plate Appearance'), ('1B', 'Single'), ('2B', 'Double'), ('3B', 'Triple'), ('IPHR', 'In-the-park Homerun'), ('HR', 'Homerun'), ('BB', 'Walk'), ('IBB', 'Intentional Walk'), ('HBP', 'Hit By Pitch'), ('KC', 'Called 3rd Strike'), ('KS', 'Strikout Swinging'), ('GIDP', 'Ground Into Double Play'), ('SACF', 'Sacrifice Fly'), ('SACH', 'Sacrifice Hit'), ("Runner's Interference", 'Ri'), ('FC', "Fielder's Choice"), ('E', 'Error')], max_length=25)),
                ('batter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='PitchingAppearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('plate_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateappearance')),
            ],
        ),
        migrations.CreateModel(
            name='FieldingPlay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('E', 'Error'), ('CI', "Catcher's Interference"), ('PO', 'Putout'), ('A', 'Assist'), ('DP', 'Double Play'), ('TP', 'Triple Play'), ('BK', 'Balk')], max_length=2)),
                ('fielder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.player')),
                ('plate_appearance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plateappearance')),
            ],
        ),
    ]
